// ============================================
// B-TECH COLLEGES DATA (TOP 35)
// ============================================

const btechColleges = [
    // --- Existing Top 20 ---
    {
        rank: 1,
        name: "IIT Madras - Indian Institute of Technology",
        location: "Chennai, Tamil Nadu",
        estYear: "1959",
        entrance: "JEE Advanced",
        fees: "₹8,00,000",
        avgPlacement: "₹21.48 LPA",
        highestPlacement: "₹1.98 Cr PA",
        specialization: "Aerospace Engineering",
        siteLink: "1"
    },
    {
        rank: 2,
        name: "IIT Delhi - Indian Institute of Technology",
        location: "New Delhi, Delhi",
        estYear: "1961",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹25.82 LPA",
        highestPlacement: "₹2.00 Cr PA",
        specialization: "Computer Science & Engg",
        siteLink: "2"
    },
    {
        rank: 3,
        name: "IIT Bombay - Indian Institute of Technology",
        location: "Mumbai, Maharashtra",
        estYear: "1958",
        entrance: "JEE Advanced",
        fees: "₹9,00,000",
        avgPlacement: "₹23.26 LPA",
        highestPlacement: "₹3.67 Cr PA",
        specialization: "Electrical Engineering",
        siteLink: "3"
    },
    {
        rank: 4,
        name: "IIT Kanpur - Indian Institute of Technology",
        location: "Kanpur, Uttar Pradesh",
        estYear: "1959",
        entrance: "JEE Advanced",
        fees: "₹8,30,000",
        avgPlacement: "₹26.27 LPA",
        highestPlacement: "₹1.90 Cr PA",
        specialization: "Mechanical Engineering",
        siteLink: "4"
    },
    {
        rank: 5,
        name: "IIT Kharagpur - Indian Institute of Technology",
        location: "Kharagpur, West Bengal",
        estYear: "1951",
        entrance: "JEE Advanced",
        fees: "₹8,40,000",
        avgPlacement: "₹19.64 LPA",
        highestPlacement: "₹2.60 Cr PA",
        specialization: "Mining Engineering",
        siteLink: "5"
    },
    {
        rank: 6,
        name: "IIT Roorkee - Indian Institute of Technology",
        location: "Roorkee, Uttarakhand",
        estYear: "1847",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹18.34 LPA",
        highestPlacement: "₹1.30 Cr PA",
        specialization: "Civil Engineering",
        siteLink: "6"
    },
    {
        rank: 7,
        name: "IIT Hyderabad - Indian Institute of Technology",
        location: "Hyderabad, Telangana",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹8,80,000",
        avgPlacement: "₹20.07 LPA",
        highestPlacement: "₹63.78 LPA",
        specialization: "Chemical Engineering",
        siteLink: "7"
    },
    {
        rank: 8,
        name: "IIT Guwahati - Indian Institute of Technology",
        location: "Guwahati, Assam",
        estYear: "1994",
        entrance: "JEE Advanced",
        fees: "₹8,60,000",
        avgPlacement: "₹25.75 LPA",
        highestPlacement: "₹2.40 Cr PA",
        specialization: "Electronics & Comm. Engg",
        siteLink: "8"
    },
    {
        rank: 9,
        name: "NIT Trichy - National Institute of Technology",
        location: "Tiruchirappalli, Tamil Nadu",
        estYear: "1964",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹12.00 LPA",
        highestPlacement: "₹42.00 LPA",
        specialization: "Production Engineering",
        siteLink: "9"
    },
    {
        rank: 10,
        name: "IIT (BHU) Varanasi",
        location: "Varanasi, Uttar Pradesh",
        estYear: "1919",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹18.96 LPA",
        highestPlacement: "₹1.20 Cr PA",
        specialization: "Metallurgical Engineering",
        siteLink: "10"
    },
    {
        rank: 11,
        name: "BITS Pilani",
        location: "Pilani, Rajasthan",
        estYear: "1964",
        entrance: "BITSAT",
        fees: "₹19,00,000",
        avgPlacement: "₹30.37 LPA",
        highestPlacement: "₹60.75 LPA",
        specialization: "Information Systems",
        siteLink: "11"
    },
    {
        rank: 12,
        name: "IIT Indore - Indian Institute of Technology",
        location: "Indore, Madhya Pradesh",
        estYear: "2009",
        entrance: "JEE Advanced",
        fees: "₹8,00,000",
        avgPlacement: "₹23.50 LPA",
        highestPlacement: "₹68.00 LPA",
        specialization: "Bioengineering",
        siteLink: "12"
    },
    {
        rank: 13,
        name: "NIT Rourkela - National Institute of Technology",
        location: "Rourkela, Odisha",
        estYear: "1961",
        entrance: "JEE Main",
        fees: "₹6,25,000",
        avgPlacement: "₹12.95 LPA",
        highestPlacement: "₹52.89 LPA",
        specialization: "Ceramic Engineering",
        siteLink: "13"
    },
    {
        rank: 14,
        name: "SRM Institute of Science and Technology",
        location: "Chennai, Tamil Nadu",
        estYear: "1985",
        entrance: "SRMJEEE",
        fees: "₹10,00,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹57.00 LPA",
        specialization: "Genetic Engineering",
        siteLink: "14"
    },
    {
        rank: 15,
        name: "IIT (ISM) Dhanbad",
        location: "Dhanbad, Jharkhand",
        estYear: "1926",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹17.01 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Petroleum Engineering",
        siteLink: "15"
    },
    {
        rank: 16,
        name: "VIT Vellore",
        location: "Vellore, Tamil Nadu",
        estYear: "1984",
        entrance: "VITEEE",
        fees: "₹7,80,000",
        avgPlacement: "₹9.23 LPA",
        highestPlacement: "₹1.02 Cr PA",
        specialization: "Biotechnology",
        siteLink: "16"
    },
    {
        rank: 17,
        name: "NIT Surathkal - National Institute of Technology",
        location: "Mangalore, Karnataka",
        estYear: "1960",
        entrance: "JEE Main",
        fees: "₹5,00,000",
        avgPlacement: "₹13.00 LPA",
        highestPlacement: "₹45.00 LPA",
        specialization: "Marine Engineering",
        siteLink: "17"
    },
    {
        rank: 18,
        name: "Jadavpur University",
        location: "Kolkata, West Bengal",
        estYear: "1955",
        entrance: "WBJEE",
        fees: "₹20,000",
        avgPlacement: "₹10.00 LPA",
        highestPlacement: "₹58.00 LPA",
        specialization: "Construction Engg",
        siteLink: "18"
    },
    {
        rank: 19,
        name: "IIT Patna - Indian Institute of Technology",
        location: "Patna, Bihar",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹8,00,000",
        avgPlacement: "₹15.00 LPA",
        highestPlacement: "₹82.05 LPA",
        specialization: "Materials Science",
        siteLink: "19"
    },
    {
        rank: 20,
        name: "Anna University",
        location: "Chennai, Tamil Nadu",
        estYear: "1978",
        entrance: "TNEA",
        fees: "₹50,000",
        avgPlacement: "₹6.50 LPA",
        highestPlacement: "₹36.00 LPA",
        specialization: "Automobile Engineering",
        siteLink: "20"
    },

    // --- Added New 15 Colleges (Rank 21-35) ---
    {
        rank: 21,
        name: "NIT Calicut - National Institute of Technology",
        location: "Kozhikode, Kerala",
        estYear: "1961",
        entrance: "JEE Main",
        fees: "₹5,00,000",
        avgPlacement: "₹13.00 LPA",
        highestPlacement: "₹45.00 LPA",
        specialization: "Architecture & Engg",
        siteLink: "21"
    },
    {
        rank: 22,
        name: "Siksha 'O' Anusandhan (SOA)",
        location: "Bhubaneswar, Odisha",
        estYear: "2007",
        entrance: "SAAT",
        fees: "₹10,50,000",
        avgPlacement: "₹6.50 LPA",
        highestPlacement: "₹42.00 LPA",
        specialization: "Computer Applications",
        siteLink: "22"
    },
    {
        rank: 23,
        name: "Amrita Vishwa Vidyapeetham",
        location: "Coimbatore, Tamil Nadu",
        estYear: "2003",
        entrance: "AEEE / JEE",
        fees: "₹12,00,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹56.00 LPA",
        specialization: "Industrial Engineering",
        siteLink: "23"
    },
    {
        rank: 24,
        name: "Jamia Millia Islamia",
        location: "New Delhi, Delhi",
        estYear: "1920",
        entrance: "JEE Main",
        fees: "₹65,000",
        avgPlacement: "₹8.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Instrumentation Engg",
        siteLink: "24"
    },
    {
        rank: 25,
        name: "IIT Gandhinagar - Indian Institute of Technology",
        location: "Gandhinagar, Gujarat",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹15.00 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Cognitive Science",
        siteLink: "25"
    },
    {
        rank: 26,
        name: "IIT Mandi - Indian Institute of Technology",
        location: "Mandi, Himachal Pradesh",
        estYear: "2009",
        entrance: "JEE Advanced",
        fees: "₹8,20,000",
        avgPlacement: "₹17.00 LPA",
        highestPlacement: "₹60.00 LPA",
        specialization: "Data Science",
        siteLink: "26"
    },
    {
        rank: 27,
        name: "IIT Jodhpur - Indian Institute of Technology",
        location: "Jodhpur, Rajasthan",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹8,30,000",
        avgPlacement: "₹16.00 LPA",
        highestPlacement: "₹55.00 LPA",
        specialization: "Smart Healthcare",
        siteLink: "27"
    },
    {
        rank: 28,
        name: "NIT Warangal - National Institute of Technology",
        location: "Warangal, Telangana",
        estYear: "1959",
        entrance: "JEE Main",
        fees: "₹5,30,000",
        avgPlacement: "₹15.50 LPA",
        highestPlacement: "₹62.00 LPA",
        specialization: "Mining Machinery Engg",
        siteLink: "28"
    },
    {
        rank: 29,
        name: "Thapar Institute of Engineering (TIET)",
        location: "Patiala, Punjab",
        estYear: "1956",
        entrance: "JEE Main",
        fees: "₹16,00,000",
        avgPlacement: "₹10.50 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Civil Infrastructure",
        siteLink: "29"
    },
    {
        rank: 30,
        name: "Delhi Technological University (DTU)",
        location: "New Delhi, Delhi",
        estYear: "1941",
        entrance: "JEE Main",
        fees: "₹7,80,000",
        avgPlacement: "₹15.00 LPA",
        highestPlacement: "₹80.00 LPA",
        specialization: "Polymer Science",
        siteLink: "30"
    },
    {
        rank: 31,
        name: "Chandigarh University (CU)",
        location: "Mohali, Punjab",
        estYear: "2012",
        entrance: "CUCET",
        fees: "₹7,50,000",
        avgPlacement: "₹5.50 LPA",
        highestPlacement: "₹45.00 LPA",
        specialization: "Robotics & Automation",
        siteLink: "31"
    },
    {
        rank: 32,
        name: "IIT Ropar - Indian Institute of Technology",
        location: "Rupnagar, Punjab",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹8,40,000",
        avgPlacement: "₹18.00 LPA",
        highestPlacement: "₹55.00 LPA",
        specialization: "Biomedical Engineering",
        siteLink: "32"
    },
    {
        rank: 33,
        name: "Kalasalingam Academy (KARE)",
        location: "Srivilliputhur, Tamil Nadu",
        estYear: "1984",
        entrance: "KALSEE",
        fees: "₹4,00,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹30.00 LPA",
        specialization: "Renewable Energy Engg",
        siteLink: "33"
    },
    {
        rank: 34,
        name: "Aligarh Muslim University (AMU)",
        location: "Aligarh, Uttar Pradesh",
        estYear: "1920",
        entrance: "AMUEEE",
        fees: "₹1,50,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Petrochemical Engg",
        siteLink: "34"
    },
    {
        rank: 35,
        name: "Koneru Lakshmaiah (KLU)",
        location: "Vaddeswaram, Andhra Pradesh",
        estYear: "1980",
        entrance: "KLUEEE",
        fees: "₹9,00,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Aerospace Engineering",
        siteLink: "35"
    },
    {
        rank: 36,
        name: "KIIT University",
        location: "Bhubaneswar, Odisha",
        estYear: "1992",
        entrance: "KIITEE",
        fees: "₹14,00,000",
        avgPlacement: "₹6.50 LPA",
        highestPlacement: "₹63.00 LPA",
        specialization: "Cyber Security",
        siteLink: "36"
    },
    {
        rank: 37,
        name: "Amity University",
        location: "Noida, Uttar Pradesh",
        estYear: "2005",
        entrance: "Amity JEE",
        fees: "₹13,50,000",
        avgPlacement: "₹5.50 LPA",
        highestPlacement: "₹61.75 LPA",
        specialization: "Artificial Intelligence",
        siteLink: "37"
    },
    {
        rank: 38,
        name: "IIIT Hyderabad",
        location: "Hyderabad, Telangana",
        estYear: "1998",
        entrance: "JEE Main / PGEE",
        fees: "₹18,00,000",
        avgPlacement: "₹30.00 LPA",
        highestPlacement: "₹1.02 Cr PA",
        specialization: "Comp. Linguistics",
        siteLink: "38"
    },
    {
        rank: 39,
        name: "IIT Bhubaneswar",
        location: "Bhubaneswar, Odisha",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹17.50 LPA",
        highestPlacement: "₹55.00 LPA",
        specialization: "Climate Science",
        siteLink: "39"
    },
    {
        rank: 40,
        name: "SASTRA University",
        location: "Thanjavur, Tamil Nadu",
        estYear: "1984",
        entrance: "JEE Main / Merit",
        fees: "₹6,00,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹27.00 LPA",
        specialization: "Mechatronics Engg",
        siteLink: "40"
    },
    {
        rank: 41,
        name: "Institute of Chemical Technology (ICT)",
        location: "Mumbai, Maharashtra",
        estYear: "1933",
        entrance: "JEE Main / MHT CET",
        fees: "₹3,50,000",
        avgPlacement: "₹7.00 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Food Engineering",
        siteLink: "41"
    },
    {
        rank: 42,
        name: "UPES Dehradun",
        location: "Dehradun, Uttarakhand",
        estYear: "2003",
        entrance: "UPES EAT",
        fees: "₹16,50,000",
        avgPlacement: "₹7.00 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Petroleum & Gas Engg",
        siteLink: "42"
    },
    {
        rank: 43,
        name: "MNIT Jaipur",
        location: "Jaipur, Rajasthan",
        estYear: "1963",
        entrance: "JEE Main",
        fees: "₹5,00,000",
        avgPlacement: "₹12.00 LPA",
        highestPlacement: "₹64.00 LPA",
        specialization: "Structural Engineering",
        siteLink: "43"
    },
    {
        rank: 44,
        name: "VNIT Nagpur",
        location: "Nagpur, Maharashtra",
        estYear: "1960",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹10.00 LPA",
        highestPlacement: "₹35.00 LPA",
        specialization: "Applied Mechanics",
        siteLink: "44"
    },
    {
        rank: 45,
        name: "Saveetha Institute (SIMATS)",
        location: "Chennai, Tamil Nadu",
        estYear: "1988",
        entrance: "SIMATS Entrance",
        fees: "₹5,00,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹12.00 LPA",
        specialization: "Biomedical Instr.",
        siteLink: "45"
    },
    {
        rank: 46,
        name: "Symbiosis International",
        location: "Pune, Maharashtra",
        estYear: "2002",
        entrance: "SITEEE",
        fees: "₹11,00,000",
        avgPlacement: "₹6.50 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Geo-Informatics",
        siteLink: "46"
    },
    {
        rank: 47,
        name: "SSN College of Engineering",
        location: "Chennai, Tamil Nadu",
        estYear: "1996",
        entrance: "TNEA / Admission Test",
        fees: "₹2,50,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹1.17 Cr PA",
        specialization: "Textile Technology",
        siteLink: "47"
    },
    {
        rank: 48,
        name: "Lovely Professional University (LPU)",
        location: "Phagwara, Punjab",
        estYear: "2005",
        entrance: "LPUNEST",
        fees: "₹9,50,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹54.00 LPA",
        specialization: "Dairy Engineering",
        siteLink: "48"
    },
    {
        rank: 49,
        name: "NIT Durgapur",
        location: "Durgapur, West Bengal",
        estYear: "1960",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹9.50 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Power Plant Engg",
        siteLink: "49"
    },
    {
        rank: 50,
        name: "NIT Silchar",
        location: "Silchar, Assam",
        estYear: "1967",
        entrance: "JEE Main",
        fees: "₹5,20,000",
        avgPlacement: "₹11.00 LPA",
        highestPlacement: "₹44.00 LPA",
        specialization: "Transport Engineering",
        siteLink: "50"
    },
    {
        rank: 51,
        name: "Birla Institute of Technology (BIT Mesra)",
        location: "Ranchi, Jharkhand",
        estYear: "1955",
        entrance: "JEE Main",
        fees: "₹14,50,000",
        avgPlacement: "₹11.57 LPA",
        highestPlacement: "₹51.00 LPA",
        specialization: "Electronics & Instrumentation",
        siteLink: "51"
    },
    {
        rank: 52,
        name: "Graphic Era University",
        location: "Dehradun, Uttarakhand",
        estYear: "2011",
        entrance: "GEU Exam",
        fees: "₹11,00,000",
        avgPlacement: "₹5.38 LPA",
        highestPlacement: "₹48.50 LPA",
        specialization: "Cloud Computing",
        siteLink: "52"
    },
    {
        rank: 53,
        name: "NIT Patna",
        location: "Patna, Bihar",
        estYear: "1886",
        entrance: "JEE Main",
        fees: "₹5,60,000",
        avgPlacement: "₹8.80 LPA",
        highestPlacement: "₹52.00 LPA",
        specialization: "Electrical & Electronics",
        siteLink: "53"
    },
    {
        rank: 54,
        name: "IIEST Shibpur",
        location: "Howrah, West Bengal",
        estYear: "1856",
        entrance: "JEE Main",
        fees: "₹5,00,000",
        avgPlacement: "₹10.50 LPA",
        highestPlacement: "₹45.00 LPA",
        specialization: "Information Technology",
        siteLink: "54"
    },
    {
        rank: 55,
        name: "NIT Delhi",
        location: "New Delhi, Delhi",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹6,00,000",
        avgPlacement: "₹12.00 LPA",
        highestPlacement: "₹82.00 LPA",
        specialization: "Computer Engineering",
        siteLink: "55"
    },
    {
        rank: 56,
        name: "IIT Jammu",
        location: "Jammu, J&K",
        estYear: "2016",
        entrance: "JEE Advanced",
        fees: "₹8,00,000",
        avgPlacement: "₹11.00 LPA",
        highestPlacement: "₹53.00 LPA",
        specialization: "Mechanical Engineering",
        siteLink: "56"
    },
    {
        rank: 57,
        name: "IIT Tirupati",
        location: "Tirupati, Andhra Pradesh",
        estYear: "2015",
        entrance: "JEE Advanced",
        fees: "₹8,20,000",
        avgPlacement: "₹10.50 LPA",
        highestPlacement: "₹46.00 LPA",
        specialization: "Civil & Environmental Engg",
        siteLink: "57"
    },
    {
        rank: 58,
        name: "Manipal University Jaipur",
        location: "Jaipur, Rajasthan",
        estYear: "2011",
        entrance: "MU-OET",
        fees: "₹16,00,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹55.00 LPA",
        specialization: "Chemical Engineering",
        siteLink: "58"
    },
    {
        rank: 59,
        name: "Manipal Institute of Technology (MIT)",
        location: "Manipal, Karnataka",
        estYear: "1957",
        entrance: "MET",
        fees: "₹18,50,000",
        avgPlacement: "₹10.50 LPA",
        highestPlacement: "₹54.75 LPA",
        specialization: "Production & Industrial Engg",
        siteLink: "59"
    },
    {
        rank: 60,
        name: "IIST (Indian Inst. of Space Science)",
        location: "Thiruvananthapuram, Kerala",
        estYear: "2007",
        entrance: "JEE Advanced",
        fees: "₹5,00,000",
        avgPlacement: "₹10.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Avionics",
        siteLink: "60"
    },
    {
        rank: 61,
        name: "MMMUT Gorakhpur",
        location: "Gorakhpur, Uttar Pradesh",
        estYear: "2013",
        entrance: "JEE Main",
        fees: "₹4,00,000",
        avgPlacement: "₹6.80 LPA",
        highestPlacement: "₹52.00 LPA",
        specialization: "Power Electronics",
        siteLink: "61"
    },
    {
        rank: 62,
        name: "NIT Raipur",
        location: "Raipur, Chhattisgarh",
        estYear: "1956",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹9.50 LPA",
        highestPlacement: "₹55.00 LPA",
        specialization: "Mining & Metallurgy",
        siteLink: "62"
    },
    {
        rank: 63,
        name: "IIIT Allahabad",
        location: "Prayagraj, Uttar Pradesh",
        estYear: "1999",
        entrance: "JEE Main",
        fees: "₹6,50,000",
        avgPlacement: "₹28.00 LPA",
        highestPlacement: "₹1.21 Cr PA",
        specialization: "Electronics & Communication",
        siteLink: "63"
    },
    {
        rank: 64,
        name: "Sathyabama Institute",
        location: "Chennai, Tamil Nadu",
        estYear: "2001",
        entrance: "Sathyabama Exam",
        fees: "₹10,00,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹53.00 LPA",
        specialization: "Nano Technology",
        siteLink: "64"
    },
    {
        rank: 65,
        name: "PSG College of Technology",
        location: "Coimbatore, Tamil Nadu",
        estYear: "1951",
        entrance: "TNEA",
        fees: "₹2,50,000",
        avgPlacement: "₹10.00 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Textile Technology",
        siteLink: "65"
    },
    {
        rank: 66,
        name: "NIT Meghalaya",
        location: "Shillong, Meghalaya",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹5,30,000",
        avgPlacement: "₹7.00 LPA",
        highestPlacement: "₹30.00 LPA",
        specialization: "Civil Engineering",
        siteLink: "66"
    },
    {
        rank: 67,
        name: "Visvesvaraya Tech University (VTU)",
        location: "Belagavi, Karnataka",
        estYear: "1998",
        entrance: "KCET",
        fees: "₹3,00,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Information Science",
        siteLink: "67"
    },
    {
        rank: 68,
        name: "DIAT (Defence Institute)",
        location: "Pune, Maharashtra",
        estYear: "1967",
        entrance: "GATE",
        fees: "₹4,00,000",
        avgPlacement: "₹12.00 LPA",
        highestPlacement: "₹35.00 LPA",
        specialization: "Quantum Computing",
        siteLink: "68"
    },
    {
        rank: 69,
        name: "IIIT Bangalore",
        location: "Bengaluru, Karnataka",
        estYear: "1999",
        entrance: "JEE Main",
        fees: "₹22,00,000",
        avgPlacement: "₹26.00 LPA",
        highestPlacement: "₹65.00 LPA",
        specialization: "Computer Science",
        siteLink: "69"
    },
    {
        rank: 70,
        name: "Netaji Subhas University (NSUT)",
        location: "New Delhi, Delhi",
        estYear: "1983",
        entrance: "JEE Main",
        fees: "₹8,50,000",
        avgPlacement: "₹16.00 LPA",
        highestPlacement: "₹1.00 Cr PA",
        specialization: "Manufacturing Processes",
        siteLink: "70"
    },
    {
        rank: 71,
        name: "Banasthali Vidyapith",
        location: "Banasthali, Rajasthan",
        estYear: "1935",
        entrance: "Aptitude Test",
        fees: "₹5,50,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Chemical Technology",
        siteLink: "71"
    },
    {
        rank: 72,
        name: "IIT Bhilai",
        location: "Bhilai, Chhattisgarh",
        estYear: "2016",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹14.00 LPA",
        highestPlacement: "₹28.00 LPA",
        specialization: "Data Science and AI",
        siteLink: "72"
    },
    {
        rank: 73,
        name: "NIT Srinagar",
        location: "Srinagar, J&K",
        estYear: "1960",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹8.00 LPA",
        highestPlacement: "₹18.00 LPA",
        specialization: "Chemical Engineering",
        siteLink: "73"
    },
    {
        rank: 74,
        name: "University of Hyderabad",
        location: "Hyderabad, Telangana",
        estYear: "1974",
        entrance: "UoH Entrance",
        fees: "₹2,00,000",
        avgPlacement: "₹9.00 LPA",
        highestPlacement: "₹23.00 LPA",
        specialization: "Computer Science",
        siteLink: "74"
    },
    {
        rank: 75,
        name: "M. S. Ramaiah Institute of Technology",
        location: "Bengaluru, Karnataka",
        estYear: "1962",
        entrance: "KCET / COMEDK",
        fees: "₹3,50,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Telecommunication Engg",
        siteLink: "75"
    },
    {
        rank: 76,
        name: "Christ University",
        location: "Bengaluru, Karnataka",
        estYear: "1969",
        entrance: "CUET",
        fees: "₹8,50,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Civil Infrastructure",
        siteLink: "76"
    },
    {
        rank: 77,
        name: "IIT Dharwad",
        location: "Dharwad, Karnataka",
        estYear: "2016",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹15.00 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Electrical and Computer Engg",
        siteLink: "77"
    },
    {
        rank: 78,
        name: "Rajiv Gandhi Institute of Petroleum Tech",
        location: "Amethi, Uttar Pradesh",
        estYear: "2008",
        entrance: "JEE Advanced",
        fees: "₹10,00,000",
        avgPlacement: "₹10.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Petroleum Engineering",
        siteLink: "78"
    },
    {
        rank: 79,
        name: "NIT Agartala",
        location: "Agartala, Tripura",
        estYear: "1965",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹9.00 LPA",
        highestPlacement: "₹35.00 LPA",
        specialization: "Production Engineering",
        siteLink: "79"
    },
    {
        rank: 80,
        name: "COEP Technological University",
        location: "Pune, Maharashtra",
        estYear: "1854",
        entrance: "MHT CET / JEE Main",
        fees: "₹4,00,000",
        avgPlacement: "₹11.00 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Robotics and AI",
        siteLink: "80"
    },
    {
        rank: 81,
        name: "NIT Kurukshetra",
        location: "Kurukshetra, Haryana",
        estYear: "1963",
        entrance: "JEE Main",
        fees: "₹6,00,000",
        avgPlacement: "₹13.00 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Industrial and Management Engg",
        siteLink: "81"
    },
    {
        rank: 82,
        name: "Sri Krishna College of Engg & Tech",
        location: "Coimbatore, Tamil Nadu",
        estYear: "1979",
        entrance: "TNEA",
        fees: "₹2,50,000",
        avgPlacement: "₹5.50 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Biomedical Engineering",
        siteLink: "82"
    },
    {
        rank: 83,
        name: "IIIT Delhi",
        location: "New Delhi, Delhi",
        estYear: "2008",
        entrance: "JEE Main / IIITD Exam",
        fees: "₹18,00,000",
        avgPlacement: "₹20.00 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Computer Science",
        siteLink: "83"
    },
    {
        rank: 84,
        name: "Vel Tech Rangarajan Dr. Sagunthala R&D",
        location: "Chennai, Tamil Nadu",
        estYear: "1997",
        entrance: "VTUEEE",
        fees: "₹10,00,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Electrical and Electronics Engg",
        siteLink: "84"
    },
    {
        rank: 85,
        name: "Andhra University College of Engg",
        location: "Visakhapatnam, Andhra Pradesh",
        estYear: "1946",
        entrance: "AP EAMCET",
        fees: "₹50,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹12.00 LPA",
        specialization: "Naval Architecture",
        siteLink: "85"
    },
    {
        rank: 86,
        name: "Chitkara University",
        location: "Rajpura, Punjab",
        estYear: "2002",
        entrance: "CEE",
        fees: "₹8,00,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹30.00 LPA",
        specialization: "Computer Science",
        siteLink: "86"
    },
    {
        rank: 87,
        name: "SR University",
        location: "Warangal, Telangana",
        estYear: "2018",
        entrance: "SRU Exam",
        fees: "₹9,00,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Data Science",
        siteLink: "87"
    },
    {
        rank: 88,
        name: "Panjab University",
        location: "Chandigarh",
        estYear: "1882",
        entrance: "JEE Main / PUCET",
        fees: "₹1,00,000",
        avgPlacement: "₹8.00 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Electronics and Communication",
        siteLink: "88"
    },
    {
        rank: 89,
        name: "JNTU Hyderabad",
        location: "Hyderabad, Telangana",
        estYear: "1972",
        entrance: "TS EAMCET",
        fees: "₹1,00,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹30.00 LPA",
        specialization: "Computer Science",
        siteLink: "89"
    },
    {
        rank: 90,
        name: "C.V. Raman Global University",
        location: "Bhubaneswar, Odisha",
        estYear: "1997",
        entrance: "CVRGEET",
        fees: "₹7,00,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Marine Engineering",
        siteLink: "90"
    },
    {
        rank: 91,
        name: "Karunya Institute of Technology",
        location: "Coimbatore, Tamil Nadu",
        estYear: "1986",
        entrance: "KEE",
        fees: "₹10,00,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Aerospace Engineering",
        siteLink: "91"
    },
    {
        rank: 92,
        name: "Kumaraguru College of Technology",
        location: "Coimbatore, Tamil Nadu",
        estYear: "1984",
        entrance: "TNEA",
        fees: "₹4,00,000",
        avgPlacement: "₹5.50 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Mechatronics Engineering",
        siteLink: "92"
    },
    {
        rank: 93,
        name: "NIT Manipur",
        location: "Imphal, Manipur",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹5,20,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹30.00 LPA",
        specialization: "Civil Engineering",
        siteLink: "93"
    },
    {
        rank: 94,
        name: "Dayananda Sagar College of Engg",
        location: "Bengaluru, Karnataka",
        estYear: "1979",
        entrance: "KCET / COMEDK",
        fees: "₹10,00,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Information Science",
        siteLink: "94"
    },
    {
        rank: 95,
        name: "Jaypee Institute of IT (JIIT)",
        location: "Noida, Uttar Pradesh",
        estYear: "2001",
        entrance: "JEE Main / JIIT Exam",
        fees: "₹12,00,000",
        avgPlacement: "₹9.00 LPA",
        highestPlacement: "₹45.00 LPA",
        specialization: "Computer Science",
        siteLink: "95"
    },
    {
        rank: 96,
        name: "NIT Goa",
        location: "Ponda, Goa",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹8.50 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Electrical and Electronics Engg",
        siteLink: "96"
    },
    {
        rank: 97,
        name: "IIITD&M Kancheepuram",
        location: "Chennai, Tamil Nadu",
        estYear: "2007",
        entrance: "JEE Main",
        fees: "₹5,80,000",
        avgPlacement: "₹11.00 LPA",
        highestPlacement: "₹42.00 LPA",
        specialization: "Smart Manufacturing",
        siteLink: "97"
    },
    {
        rank: 98,
        name: "Vignan's Foundation for Science",
        location: "Guntur, Andhra Pradesh",
        estYear: "1997",
        entrance: "V-SAT",
        fees: "₹8,00,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹18.00 LPA",
        specialization: "Food Technology",
        siteLink: "98"
    },
    {
        rank: 99,
        name: "B.M.S. College of Engineering",
        location: "Bengaluru, Karnataka",
        estYear: "1946",
        entrance: "KCET / COMEDK",
        fees: "₹9,50,000",
        avgPlacement: "₹8.00 LPA",
        highestPlacement: "₹48.00 LPA",
        specialization: "Mechanical Engineering",
        siteLink: "99"
    },
    {
        rank: 100,
        name: "Siddaganga Institute of Technology",
        location: "Tumkur, Karnataka",
        estYear: "1963",
        entrance: "KCET / COMEDK",
        fees: "₹4,50,000",
        avgPlacement: "₹5.50 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Industrial Engineering",
        siteLink: "100"
    },
    {
        rank: 101,
        name: "Amity University Haryana",
        location: "Gurugram, Haryana",
        estYear: "2010",
        entrance: "Amity JEE",
        fees: "₹13,00,000",
        avgPlacement: "₹6.50 LPA",
        highestPlacement: "₹30.00 LPA",
        specialization: "Computer Science and Engg",
        siteLink: "101"
    },
    {
        rank: 102,
        name: "Amity University Kolkata",
        location: "Kolkata, West Bengal",
        estYear: "2015",
        entrance: "Amity JEE",
        fees: "₹8,50,000",
        avgPlacement: "₹5.80 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Data Science",
        siteLink: "102"
    },
    {
        rank: 103,
        name: "Anurag University",
        location: "Hyderabad, Telangana",
        estYear: "2005",
        entrance: "TS EAMCET",
        fees: "₹4,50,000",
        avgPlacement: "₹4.20 LPA",
        highestPlacement: "₹18.00 LPA",
        specialization: "Chemical Technology",
        siteLink: "103"
    },
    {
        rank: 104,
        name: "Bansilal Ramnath Agarwal (VIT Pune)",
        location: "Pune, Maharashtra",
        estYear: "1983",
        entrance: "JEE Main / MHT CET",
        fees: "₹7,20,000",
        avgPlacement: "₹7.50 LPA",
        highestPlacement: "₹35.00 LPA",
        specialization: "Electronics and Telecommunication",
        siteLink: "104"
    },
    {
        rank: 105,
        name: "Chandigarh Engineering College (CGC)",
        location: "Mohali, Punjab",
        estYear: "2001",
        entrance: "CUCET / JEE Main",
        fees: "₹4,00,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹28.00 LPA",
        specialization: "Robotics",
        siteLink: "105"
    },
    {
        rank: 106,
        name: "Chennai Institute of Technology",
        location: "Chennai, Tamil Nadu",
        estYear: "2010",
        entrance: "TNEA",
        fees: "₹3,50,000",
        avgPlacement: "₹4.80 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Mechatronics Engineering",
        siteLink: "106"
    },
    {
        rank: 107,
        name: "Coimbatore Institute of Technology",
        location: "Coimbatore, Tamil Nadu",
        estYear: "1956",
        entrance: "TNEA",
        fees: "₹2,80,000",
        avgPlacement: "₹5.50 LPA",
        highestPlacement: "₹22.00 LPA",
        specialization: "Civil Engineering",
        siteLink: "107"
    },
    {
        rank: 108,
        name: "College of Engineering Trivandrum (CET)",
        location: "Thiruvananthapuram, Kerala",
        estYear: "1939",
        entrance: "KEAM",
        fees: "₹60,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Electrical Engineering",
        siteLink: "108"
    },
    {
        rank: 109,
        name: "Dr. Vishwanath Karad MIT-WPU",
        location: "Pune, Maharashtra",
        estYear: "2017",
        entrance: "MHT CET / JEE Main",
        fees: "₹12,50,000",
        avgPlacement: "₹6.80 LPA",
        highestPlacement: "₹32.00 LPA",
        specialization: "Petroleum Engineering",
        siteLink: "109"
    },
    {
        rank: 110,
        name: "Easwari Engineering College",
        location: "Chennai, Tamil Nadu",
        estYear: "1996",
        entrance: "TNEA",
        fees: "₹2,50,000",
        avgPlacement: "₹4.00 LPA",
        highestPlacement: "₹14.00 LPA",
        specialization: "Information Technology",
        siteLink: "110"
    },
    {
        rank: 111,
        name: "Galgotias University",
        location: "Greater Noida, Uttar Pradesh",
        estYear: "2011",
        entrance: "Galgotias Entrance Test",
        fees: "₹6,50,000",
        avgPlacement: "₹5.20 LPA",
        highestPlacement: "₹26.00 LPA",
        specialization: "Biomedical Engineering",
        siteLink: "111"
    },
    {
        rank: 112,
        name: "GITAM University",
        location: "Visakhapatnam, Andhra Pradesh",
        estYear: "1980",
        entrance: "GITAM GAT",
        fees: "₹10,50,000",
        avgPlacement: "₹6.30 LPA",
        highestPlacement: "₹29.00 LPA",
        specialization: "Aerospace Engineering",
        siteLink: "112"
    },
    {
        rank: 113,
        name: "GGSIPU (Indraprastha University)",
        location: "New Delhi, Delhi",
        estYear: "1998",
        entrance: "JEE Main",
        fees: "₹5,00,000",
        avgPlacement: "₹7.00 LPA",
        highestPlacement: "₹33.00 LPA",
        specialization: "Mechanical Engineering",
        siteLink: "113"
    },
    {
        rank: 114,
        name: "Hindustan Institute of Tech & Science",
        location: "Chennai, Tamil Nadu",
        estYear: "1985",
        entrance: "HITSEEE",
        fees: "₹9,00,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹16.00 LPA",
        specialization: "Aeronautical Engineering",
        siteLink: "114"
    },
    {
        rank: 115,
        name: "IIIT Allahabad",
        location: "Prayagraj, Uttar Pradesh",
        estYear: "1999",
        entrance: "JEE Main / GATE",
        fees: "₹6,80,000",
        avgPlacement: "₹14.00 LPA",
        highestPlacement: "₹65.00 LPA",
        specialization: "Computer Science",
        siteLink: "115"
    },
    {
        rank: 116,
        name: "IIT Goa",
        location: "Ponda, Goa",
        estYear: "2016",
        entrance: "JEE Advanced",
        fees: "₹8,50,000",
        avgPlacement: "₹15.50 LPA",
        highestPlacement: "₹80.00 LPA",
        specialization: "Electrical Engineering",
        siteLink: "116"
    },
    {
        rank: 117,
        name: "JNTU Kakinada",
        location: "Kakinada, Andhra Pradesh",
        estYear: "1946",
        entrance: "AP EAMCET",
        fees: "₹60,000",
        avgPlacement: "₹4.70 LPA",
        highestPlacement: "₹19.00 LPA",
        specialization: "Civil Engineering",
        siteLink: "117"
    },
    {
        rank: 118,
        name: "Jaypee Institute of Info. Tech",
        location: "Noida, Uttar Pradesh",
        estYear: "2001",
        entrance: "JEE Main / JIIT Exam",
        fees: "₹11,00,000",
        avgPlacement: "₹7.80 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Electronics & Communication",
        siteLink: "118"
    },
    {
        rank: 119,
        name: "Kongu Engineering College",
        location: "Erode, Tamil Nadu",
        estYear: "1984",
        entrance: "TNEA",
        fees: "₹2,50,000",
        avgPlacement: "₹5.30 LPA",
        highestPlacement: "₹21.00 LPA",
        specialization: "Food Technology",
        siteLink: "119"
    },
    {
        rank: 120,
        name: "KPR Institute of Engineering & Tech",
        location: "Coimbatore, Tamil Nadu",
        estYear: "2009",
        entrance: "TNEA",
        fees: "₹3,00,000",
        avgPlacement: "₹4.10 LPA",
        highestPlacement: "₹13.00 LPA",
        specialization: "Artificial Intelligence",
        siteLink: "120"
    },
    {
        rank: 121,
        name: "Maharishi Markandeshwar",
        location: "Ambala, Haryana",
        estYear: "1993",
        entrance: "MMU CET",
        fees: "₹11,50,000",
        avgPlacement: "₹5.90 LPA",
        highestPlacement: "₹24.00 LPA",
        specialization: "Computer Science & Engg",
        siteLink: "121"
    },
    {
        rank: 122,
        name: "Mahindra University",
        location: "Hyderabad, Telangana",
        estYear: "2020",
        entrance: "JEE Main / EAMCET",
        fees: "₹18,00,000",
        avgPlacement: "₹7.20 LPA",
        highestPlacement: "₹34.00 LPA",
        specialization: "Interdisciplinary Engineering",
        siteLink: "122"
    },
    {
        rank: 123,
        name: "Manav Rachna Int. Institute",
        location: "Faridabad, Haryana",
        estYear: "1997",
        entrance: "MRNAT",
        fees: "₹10,50,000",
        avgPlacement: "₹6.10 LPA",
        highestPlacement: "₹27.00 LPA",
        specialization: "Automobile Engineering",
        siteLink: "123"
    },
    {
        rank: 124,
        name: "Maulana Azad National Urdu University",
        location: "Hyderabad, Telangana",
        estYear: "1998",
        entrance: "JEE Main",
        fees: "₹1,50,000",
        avgPlacement: "₹3.80 LPA",
        highestPlacement: "₹12.00 LPA",
        specialization: "Electronics Engineering",
        siteLink: "124"
    },
    {
        rank: 125,
        name: "NIFTEM",
        location: "Sonipat, Haryana",
        estYear: "2012",
        entrance: "JEE Main",
        fees: "₹7,00,000",
        avgPlacement: "₹5.40 LPA",
        highestPlacement: "₹23.00 LPA",
        specialization: "Food Technology & Management",
        siteLink: "125"
    },
    {
        rank: 126,
        name: "NIFTEM Thanjavur",
        location: "Thanjavur, Tamil Nadu",
        estYear: "2012",
        entrance: "JEE Main",
        fees: "₹6,80,000",
        avgPlacement: "₹4.90 LPA",
        highestPlacement: "₹17.00 LPA",
        specialization: "Food Processing Engineering",
        siteLink: "126"
    },
    {
        rank: 127,
        name: "NIT Arunachal Pradesh",
        location: "Itanagar, Arunachal Pradesh",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹5,50,000",
        avgPlacement: "₹6.40 LPA",
        highestPlacement: "₹31.00 LPA",
        specialization: "Mechanical Engineering",
        siteLink: "127"
    },
    {
        rank: 128,
        name: "NIT Mizoram",
        location: "Aizawl, Mizoram",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹5,20,000",
        avgPlacement: "₹5.10 LPA",
        highestPlacement: "₹18.00 LPA",
        specialization: "Electrical and Electronics Engg",
        siteLink: "128"
    },
    {
        rank: 129,
        name: "NIT Nagaland",
        location: "Dimapur, Nagaland",
        estYear: "2010",
        entrance: "JEE Main",
        fees: "₹5,30,000",
        avgPlacement: "₹5.60 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Computer Science",
        siteLink: "129"
    },
    {
        rank: 130,
        name: "Nirma University",
        location: "Ahmedabad, Gujarat",
        estYear: "2003",
        entrance: "JEE Main / GUJCET",
        fees: "₹10,00,000",
        avgPlacement: "₹7.60 LPA",
        highestPlacement: "₹36.00 LPA",
        specialization: "Civil Engineering",
        siteLink: "130"
    },
    {
        rank: 131,
        name: "Nitte Meenakshi Institute of Tech",
        location: "Bengaluru, Karnataka",
        estYear: "1984",
        entrance: "KCET / COMEDK",
        fees: "₹9,50,000",
        avgPlacement: "₹6.20 LPA",
        highestPlacement: "₹29.00 LPA",
        specialization: "Aerospace Engineering",
        siteLink: "131"
    },
    {
        rank: 132,
        name: "Noida Institute of Engg & Tech (NIET)",
        location: "Greater Noida, Uttar Pradesh",
        estYear: "2001",
        entrance: "UPSEE / JEE Main",
        fees: "₹6,00,000",
        avgPlacement: "₹5.70 LPA",
        highestPlacement: "₹25.00 LPA",
        specialization: "Robotics and Automation",
        siteLink: "132"
    },
    {
        rank: 133,
        name: "IIITDM Jabalpur",
        location: "Jabalpur, Madhya Pradesh",
        estYear: "2005",
        entrance: "JEE Main",
        fees: "₹5,80,000",
        avgPlacement: "₹10.50 LPA",
        highestPlacement: "₹45.00 LPA",
        specialization: "Design and Manufacturing",
        siteLink: "133"
    },
    {
        rank: 134,
        name: "PES University",
        location: "Bengaluru, Karnataka",
        estYear: "1988",
        entrance: "PESSAT",
        fees: "₹14,50,000",
        avgPlacement: "₹8.00 LPA",
        highestPlacement: "₹42.00 LPA",
        specialization: "Computer Science & Design",
        siteLink: "134"
    },
    {
        rank: 135,
        name: "PSG Institute of Tech & Applied Research",
        location: "Coimbatore, Tamil Nadu",
        estYear: "2014",
        entrance: "TNEA",
        fees: "₹3,50,000",
        avgPlacement: "₹4.60 LPA",
        highestPlacement: "₹16.00 LPA",
        specialization: "Internet of Things",
        siteLink: "135"
    },
    {
        rank: 136,
        name: "Punjab Engineering College (PEC)",
        location: "Chandigarh",
        estYear: "1921",
        entrance: "JEE Main",
        fees: "₹7,50,000",
        avgPlacement: "₹11.00 LPA",
        highestPlacement: "₹50.00 LPA",
        specialization: "Production Engineering",
        siteLink: "136"
    },
    {
        rank: 137,
        name: "R.V. College of Engineering",
        location: "Bengaluru, Karnataka",
        estYear: "1963",
        entrance: "KCET / COMEDK",
        fees: "₹10,00,000",
        avgPlacement: "₹9.50 LPA",
        highestPlacement: "₹48.00 LPA",
        specialization: "Electronics & Communication",
        siteLink: "137"
    },
    {
        rank: 138,
        name: "Rajalakshmi Engineering College",
        location: "Chennai, Tamil Nadu",
        estYear: "1997",
        entrance: "TNEA",
        fees: "₹4,00,000",
        avgPlacement: "₹4.30 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Bio-Medical Engineering",
        siteLink: "138"
    },
    {
        rank: 139,
        name: "Sharda University",
        location: "Greater Noida, Uttar Pradesh",
        estYear: "2009",
        entrance: "SUAT",
        fees: "₹9,00,000",
        avgPlacement: "₹5.00 LPA",
        highestPlacement: "₹20.00 LPA",
        specialization: "Artificial Intelligence",
        siteLink: "139"
    },
    {
        rank: 140,
        name: "Shoolini University",
        location: "Solan, Himachal Pradesh",
        estYear: "2009",
        entrance: "SU Aptitude Test",
        fees: "₹8,50,000",
        avgPlacement: "₹3.90 LPA",
        highestPlacement: "₹13.00 LPA",
        specialization: "Biotechnology",
        siteLink: "140"
    },
    {
        rank: 141,
        name: "SVKM's NMIMS",
        location: "Mumbai, Maharashtra",
        estYear: "1981",
        entrance: "NMIMS-CET",
        fees: "₹13,50,000",
        avgPlacement: "₹8.50 LPA",
        highestPlacement: "₹40.00 LPA",
        specialization: "Data Science",
        siteLink: "141"
    },
    {
        rank: 142,
        name: "The Northcap University",
        location: "Gurugram, Haryana",
        estYear: "1996",
        entrance: "JEE Main / NCAT",
        fees: "₹10,00,000",
        avgPlacement: "₹6.00 LPA",
        highestPlacement: "₹28.00 LPA",
        specialization: "Cyber Security",
        siteLink: "142"
    },
    {
        rank: 143,
        name: "Thiagarajar College of Engineering",
        location: "Madurai, Tamil Nadu",
        estYear: "1957",
        entrance: "TNEA",
        fees: "₹2,50,000",
        avgPlacement: "₹5.20 LPA",
        highestPlacement: "₹21.00 LPA",
        specialization: "Structural Engineering",
        siteLink: "143"
    },
    {
        rank: 144,
        name: "University College of Engineering",
        location: "Hyderabad, Telangana",
        estYear: "1929",
        entrance: "TS EAMCET",
        fees: "₹1,00,000",
        avgPlacement: "₹4.40 LPA",
        highestPlacement: "₹16.00 LPA",
        specialization: "Mining Engineering",
        siteLink: "144"
    },
    {
        rank: 145,
        name: "University of Allahabad",
        location: "Prayagraj, Uttar Pradesh",
        estYear: "1887",
        entrance: "AU Admission Test",
        fees: "₹40,000",
        avgPlacement: "₹3.70 LPA",
        highestPlacement: "₹11.00 LPA",
        specialization: "Electronics and Communication",
        siteLink: "145"
    },
    {
        rank: 146,
        name: "VJTI Mumbai",
        location: "Mumbai, Maharashtra",
        estYear: "1887",
        entrance: "MHT CET / JEE Main",
        fees: "₹3,50,000",
        avgPlacement: "₹8.80 LPA",
        highestPlacement: "₹44.00 LPA",
        specialization: "Textile Technology",
        siteLink: "146"
    },
    {
        rank: 147,
        name: "Vel Tech Rangarajan",
        location: "Chennai, Tamil Nadu",
        estYear: "1997",
        entrance: "VTUEEE",
        fees: "₹8,50,000",
        avgPlacement: "₹4.50 LPA",
        highestPlacement: "₹17.00 LPA",
        specialization: "Electrical and Electronics Engg",
        siteLink: "147"
    },
    {
        rank: 148,
        name: "Vels Institute (VISTAS)",
        location: "Chennai, Tamil Nadu",
        estYear: "1992",
        entrance: "VEE",
        fees: "₹7,00,000",
        avgPlacement: "₹4.00 LPA",
        highestPlacement: "₹14.00 LPA",
        specialization: "Marine Engineering",
        siteLink: "148"
    },
    {
        rank: 149,
        name: "Vignan Institute",
        location: "Hyderabad, Telangana",
        estYear: "1999",
        entrance: "TS EAMCET",
        fees: "₹4,50,000",
        avgPlacement: "₹4.10 LPA",
        highestPlacement: "₹15.00 LPA",
        specialization: "Computer Science",
        siteLink: "149"
    },
    {
        rank: 150,
        name: "Vishwakarma Institute of Technology (VIT)",
        location: "Pune, Maharashtra",
        estYear: "1983",
        entrance: "MHT CET / JEE Main",
        fees: "₹7,50,000",
        avgPlacement: "₹7.30 LPA",
        highestPlacement: "₹38.00 LPA",
        specialization: "Industrial Engineering",
        siteLink: "150"
    }
];

// Function to populate table
function populateBTechTable() {
    const tbody = document.getElementById('btechCollegesTableBody');
    
    // Check if element exists to avoid errors on other pages
    if (!tbody) return;

    tbody.innerHTML = '';

    btechColleges.forEach(college => {
        const row = document.createElement('tr');
        
        row.innerHTML = `
            <td class="rank-cell">
                <div class="rank-badge" style="border-color: #3b82f6; color: #1d4ed8; background: #eff6ff;">${college.rank}</div>
            </td>
            <td>
                <div class="college-name">${college.name}</div>
                <div class="college-location">${college.location}</div>
            </td>
            <td style="font-weight: 500; color: #555;">${college.estYear}</td>
            
            <td style="font-weight: 600; color: #e11d48; font-size: 13px;">${college.entrance}</td>

            <td class="fee-cell">${college.fees}</td>
            <td class="placement-cell">${college.avgPlacement}</td>
            <td class="highest-placement-cell">
                ${college.highestPlacement}
            </td>
            <td style="font-size: 13px; color: #4b5563; max-width: 150px;">
                ${college.specialization}
            </td>
            <td style="text-align: center;">
                <a href="college-site.html?id=BTech-${college.rank}" class="site-btn">View Site</a>
            </td>
        `;
        
        tbody.appendChild(row);
    });
    
    console.log('✅ B-Tech Colleges table populated with 35 colleges');
}

// Initialize when the DOM is fully loaded
document.addEventListener('DOMContentLoaded', function() {
    populateBTechTable();
});